FROM mcr.microsoft.com/dotnet/aspnet:5.0-focal AS base
WORKDIR /app

LABEL author="Viktor Prykhidko"

ENV ASPNETCORE_URLS=http://*:5000

FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /src
COPY ["Calypso.Api.csproj", "./"]
RUN dotnet restore "Calypso.Api.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "Calypso.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Calypso.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Calypso.Api.dll"]
